spring:
  datasource:
    url: jdbc:h2:mem:better_db_test
    driverClassName: org.h2.Driver
    username: better
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2console/